# Generated by Django 4.2 on 2023-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('pic_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Resim',
                'verbose_name_plural': 'Resimler',
            },
        ),
    ]
