# Generated by Django 4.2 on 2023-05-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_dealers_whole_saler'),
        ('picture', '0002_alter_picture_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to='company.company', verbose_name='Yükleyici'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık'),
        ),
    ]
