# Generated by Django 4.2 on 2023-05-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('surname', models.CharField(max_length=100, verbose_name='Müşteri Soyadı')),
                ('phone', models.BigIntegerField(verbose_name='Telefon Numarası')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Açık Adres')),
                ('tc_no', models.BigIntegerField(verbose_name='Tc Kimlik Numarası')),
                ('customer_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.company', verbose_name='Müşterisi Olduğu Şirket')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
    ]
