# Generated by Django 4.2 on 2023-04-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_owner_name_alter_company_owner_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='CutainManager', max_length=100)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
