# Generated by Django 4.2 on 2023-05-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='CutainManager', max_length=100, verbose_name='İsim')),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Üretici Şirket')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Renk')),
            ],
            options={
                'verbose_name': 'Renk',
                'verbose_name_plural': 'Renkler',
            },
        ),
        migrations.CreateModel(
            name='CurtainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Perde Tipi Adı')),
            ],
            options={
                'verbose_name': 'Perde Model Tipi',
                'verbose_name_plural': 'Perde Model Tipleri',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Birim Tipi Adı')),
            ],
            options={
                'verbose_name': 'Perde Birim',
                'verbose_name_plural': 'Perde Birimleri',
            },
        ),
        migrations.CreateModel(
            name='Curtain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Barkod')),
                ('variant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Varyant')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Gramaj')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Yükseklik')),
                ('w_price', models.FloatField(verbose_name='Toptan Fiyatı')),
                ('s_price', models.FloatField(verbose_name='Satış Fiyatı')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand', verbose_name='Marka')),
                ('brand_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_companies', to='company.company', verbose_name='Üretici Şirket')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.category', verbose_name='Kategori')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.color', verbose_name='Renk')),
                ('img1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img1s', to='picture.picture', verbose_name='Resim1')),
                ('img2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img2s', to='picture.picture', verbose_name='Resim1')),
                ('img3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img3s', to='picture.picture', verbose_name='Resim1')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
