# Generated by Django 4.2 on 2023-05-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtain',
            name='code',
            field=models.CharField(max_length=200, unique=True, verbose_name='Barkod'),
        ),
    ]
