# Generated by Django 4.2 on 2023-05-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_curtain_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
    ]
