# Generated by Django 4.2 on 2023-06-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtain',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Barkod'),
        ),
    ]
