# Generated by Django 4.2 on 2023-04-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_owner_name_alter_company_owner_surname'),
        ('picture', '0002_alter_picture_pic_url'),
        ('product', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curtain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Barkod')),
                ('variant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Varyant')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Gramaj')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Yükseklik')),
                ('w_price', models.FloatField(verbose_name='Toptan Fiyatı')),
                ('s_price', models.FloatField(verbose_name='Satış Fiyatı')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand')),
                ('brand_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_companies', to='company.company')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.color')),
                ('img1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img1s', to='picture.picture')),
                ('img2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img2s', to='picture.picture')),
                ('img3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img3s', to='picture.picture')),
            ],
        ),
    ]
