# Generated by Django 4.2 on 2023-04-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_curtain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(default='CutainManager', max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Renk'),
        ),
    ]
