# Generated by Django 4.2 on 2023-04-26 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_dealers'),
        ('picture', '0002_alter_picture_pic_url'),
        ('product', '0005_alter_brand_title_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Üretici Şirket'),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand', verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='brand_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_companies', to='company.company', verbose_name='Üretici Şirket'),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.color', verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='img1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img1s', to='picture.picture', verbose_name='Resim1'),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='img2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img2s', to='picture.picture', verbose_name='Resim1'),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='img3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img3s', to='picture.picture', verbose_name='Resim1'),
        ),
    ]
