# Generated by Django 4.2 on 2023-04-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_brand_owner_alter_curtain_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Renk', 'verbose_name_plural': 'Renkler'},
        ),
        migrations.AlterModelOptions(
            name='curtain',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
