# Generated by Django 4.2 on 2023-04-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_curtaintype_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curtaintype',
            options={'verbose_name': 'Perde Model Tipi', 'verbose_name_plural': 'Perde Model Tipleri'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Perde Birim', 'verbose_name_plural': 'Perde Birimleri'},
        ),
    ]
