# Generated by Django 4.2 on 2023-05-15 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_dealers_whole_saler'),
        ('product', '0009_alter_curtaintype_options_alter_unit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtain',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='curtain',
            name='brand_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_companies', to='company.dealers', verbose_name='Üretici Şirket'),
        ),
    ]
