# Generated by Django 4.2 on 2023-05-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_dealers_whole_saler'),
        ('product', '0010_alter_curtain_brand_alter_curtain_brand_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtain',
            name='brand_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_companies', to='company.company', verbose_name='Üretici Şirket'),
        ),
    ]
