# Generated by Django 4.2 on 2023-04-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picture', '0002_alter_picture_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('owner_surname', models.CharField(max_length=100, verbose_name='Company Name')),
                ('tc_no', models.BigIntegerField(verbose_name='Personal Tax Number')),
                ('phone_number', models.BigIntegerField(verbose_name='Company Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Company Email')),
                ('tax_no', models.BigIntegerField(verbose_name='Tax Number')),
                ('tax_municipilaty', models.CharField(max_length=100, verbose_name='Municiplaty Name')),
                ('address', models.CharField(max_length=255)),
                ('tax_document_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='picture.picture')),
            ],
            options={
                'verbose_name': 'Şirket',
                'verbose_name_plural': 'Şirketler',
            },
        ),
    ]
