# Generated by Django 4.2 on 2023-05-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Owner Name')),
                ('owner_surname', models.CharField(max_length=100, verbose_name='Owner Surname')),
                ('tc_no', models.BigIntegerField(verbose_name='Personal Tax Number')),
                ('phone_number', models.BigIntegerField(verbose_name='Company Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Company Email')),
                ('tax_no', models.BigIntegerField(verbose_name='Tax Number')),
                ('tax_municipilaty', models.CharField(max_length=100, verbose_name='Municiplaty Name')),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Şirket',
                'verbose_name_plural': 'Şirketler',
            },
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dealers', to='company.company', verbose_name='Bayi ID')),
                ('whole_saler', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whole_salers', to='company.company', verbose_name='Toptancı ID')),
            ],
            options={
                'verbose_name': 'Bayi',
                'verbose_name_plural': 'Bayiler',
            },
        ),
    ]
