# Generated by Django 4.2 on 2023-04-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner_name',
            field=models.CharField(max_length=100, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_surname',
            field=models.CharField(max_length=100, verbose_name='Owner Surname'),
        ),
    ]
