# Generated by Django 4.2 on 2023-06-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='company.company', verbose_name='Bayi ID'),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='whole_saler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whole_salers', to='company.company', verbose_name='Toptancı ID'),
        ),
    ]
