# Generated by Django 4.2 on 2023-04-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_dealers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealers',
            options={'verbose_name': 'Bayi', 'verbose_name_plural': 'Bayiler'},
        ),
    ]
