# Generated by Django 4.2 on 2023-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_dealers_dealer_alter_dealers_whole_saler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Company Name'),
        ),
    ]
