# Generated by Django 4.2 on 2023-05-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_dealers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='whole_saler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whole_salers', to='company.company', verbose_name='Toptancı ID'),
        ),
    ]
