# Generated by Django 4.2 on 2023-04-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('admin', 'Admin'), ('salesman', 'Salesman'), ('worker', 'Worker')], default='worker', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Çalışan Tipi',
                'verbose_name_plural': 'Çalışan Tipleri',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=65, verbose_name='Employee Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Employee Surname')),
                ('phone_number', models.BigIntegerField(verbose_name='Employee Phone Number')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Employee Email')),
                ('tc_number', models.BigIntegerField(verbose_name='Employee National ID')),
                ('salary', models.IntegerField(blank=True, default=None, null=True, verbose_name='Salary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.usertype')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Çalışan',
                'verbose_name_plural': 'Çalışanlar',
            },
        ),
    ]
