# Generated by Django 4.2 on 2023-05-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('measurement', '0001_initial'),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Sipariş Durumu')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('unit_price', models.FloatField(verbose_name='Birim Fiyatı')),
                ('unit', models.FloatField(verbose_name='Birim Miktarı')),
                ('payment', models.FloatField(default=0, verbose_name='Sipariş İçin Yapılan Ödeme')),
                ('dealer_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dealer_companies', to='company.company', verbose_name='Bayi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dealer_products', to='product.curtain', verbose_name='Ürün')),
                ('product_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_companies', to='company.company', verbose_name='Üretici')),
            ],
            options={
                'verbose_name': 'Bayi Üretici Sipariş',
                'verbose_name_plural': 'Bayi Üretici Siparişleri',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Sipariş Durumu')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurements', to='measurement.measurement', verbose_name='Ölçüler')),
                ('measurement_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurement_groups', to='measurement.measurementgroup', verbose_name='Ölçü Grubu')),
            ],
            options={
                'verbose_name': 'Müşteri Siparişi',
                'verbose_name_plural': 'Müşteri Siparişleri',
            },
        ),
    ]
