# Generated by Django 4.2 on 2023-05-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_curtain_code'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='curtains', to='product.curtain', verbose_name='Ürün'),
        ),
    ]
