# Generated by Django 4.2 on 2023-05-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_customerorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='product',
        ),
    ]
