# Generated by Django 4.2 on 2023-05-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('order', '0003_remove_customerorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='customer.customer', verbose_name='Müşteri'),
        ),
    ]
