# Generated by Django 4.2 on 2023-05-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_customerorder_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='company',
        ),
    ]
