# Generated by Django 4.2 on 2023-05-17 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('order', '0007_remove_customerorder_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='company.company', verbose_name='Müşterinin Şirketi'),
        ),
    ]
