# Generated by Django 4.2 on 2023-05-17 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('order', '0008_customerorder_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerorder',
            name='current_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_company', to='company.company', verbose_name='Aktif Şuanki Şirket'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('preparing', 'Hazırlanıyor'), ('on_delivery', 'Teslimatta'), ('delivered', 'Teslim Edildi'), ('waiting_payment', 'Ödeme Bekliyor'), ('completed', 'Tamamlandı')], max_length=100, verbose_name='Sipariş Durumu'),
        ),
        migrations.AlterField(
            model_name='dealerorder',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('preparing', 'Hazırlanıyor'), ('on_delivery', 'Teslimatta'), ('delivered', 'Teslim Edildi'), ('waiting_payment', 'Ödeme Bekliyor'), ('completed', 'Tamamlandı')], max_length=100, verbose_name='Sipariş Durumu'),
        ),
    ]
