# Generated by Django 4.2 on 2023-05-17 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_curtain_code'),
        ('order', '0009_dealerorder_current_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.unit', verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='dealerorder',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.unit', verbose_name='Birim'),
        ),
    ]
