# Generated by Django 4.2 on 2023-05-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_customerorder_unit_alter_dealerorder_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerorder',
            name='current_company',
        ),
    ]
