# Generated by Django 4.2 on 2023-05-28 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_created_date'),
        ('measurement', '0002_measurementgroup_created_date'),
        ('order', '0011_remove_dealerorder_current_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customer.customer', verbose_name='Müşteri'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.measurement', verbose_name='Ölçüler'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='measurement_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_groups', to='measurement.measurementgroup', verbose_name='Ölçü Grubu'),
        ),
    ]
