# Generated by Django 4.2 on 2023-06-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_customerorder_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('preparing', 'Hazırlanıyor'), ('on_delivery', 'Teslimatta'), ('on_control', 'Kontrolde'), ('delivered', 'Teslim Edildi'), ('waiting_payment', 'Ödeme Bekliyor'), ('completed', 'Tamamlandı')], max_length=100, verbose_name='Sipariş Durumu'),
        ),
    ]
