# Generated by Django 4.2 on 2023-06-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_curtain_code'),
        ('order', '0013_alter_customerorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerorder',
            name='unit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.unit', verbose_name='Birim Tipi'),
        ),
        migrations.AlterField(
            model_name='dealerorder',
            name='unit',
            field=models.FloatField(verbose_name='Birim'),
        ),
    ]
