# Generated by Django 4.2 on 2023-04-27 20:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_customer_of'),
        ('product', '0009_alter_curtaintype_options_alter_unit_options'),
        ('company', '0004_alter_dealers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurtainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Perde Model Adı')),
            ],
            options={
                'verbose_name': 'Perde Modeli',
                'verbose_name_plural': 'Perde Modelleri',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Oda Adı')),
            ],
            options={
                'verbose_name': 'Oda',
                'verbose_name_plural': 'Odalar',
            },
        ),
        migrations.CreateModel(
            name='MeasurementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Ölçü Grubu Adı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company', verbose_name='Şirket Adı')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer', verbose_name='Müşteri Adı')),
            ],
            options={
                'verbose_name': 'Ölçü Grubu',
                'verbose_name_plural': 'Ölçü Grupları',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(validators=[django.core.validators.MaxValueValidator(600), django.core.validators.MinValueValidator(30)], verbose_name='Genişlik')),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(600), django.core.validators.MinValueValidator(50)], verbose_name='Yükseklik')),
                ('measurement_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ölçü Notu')),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Birim Fiyatı')),
                ('room_pic', models.ImageField(upload_to='measurement/windows/%Y/%m/%d', verbose_name='Pencere Resmi')),
                ('measurement_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='measurement.measurementgroup', verbose_name='Ölçü Grup Idsi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.curtain', verbose_name='Ürün')),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='measurement.room', verbose_name='Oda Adı')),
            ],
            options={
                'verbose_name': 'Ölçü',
                'verbose_name_plural': 'Ölçüler',
            },
        ),
    ]
