# Generated by Django 4.2 on 2023-05-28 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurementgroup_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='type',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(3)], verbose_name='Pile/Tip'),
        ),
    ]
