# Generated by Django 4.2 on 2023-06-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementgroup',
            name='order_status',
            field=models.BooleanField(default=False, verbose_name='Sipariş Durumu'),
        ),
    ]
